config/routes.rb
GenQR::Application.routes.draw do 

  
  
  resources :assets  do 
    member do
      get 'remove_template'
      get 'all_sticker'
      get 'download_sticker'
      get 'validation_error'
      get 'print_sticker'
    end
    collection do 
      get 'failed_asset'
    end
  end
  
  resources :sticker_templates do
    member do 
      get 'sample_template'
      put 'update_copy'
    end  
  end

  mount Resque::Server.new, :at => "/resque"

  
  
  match '/welcome' => "home#index",:as => :home
  match '/thank_you' => "home#thank_you",:as => :thank_you  

  devise_for :users

  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout
  end

  resources :users 
  

  
  resources :products do 
    member do 
      get 'qrcode_image'
      get 'regenerate_qrcode'
    end
  end
  
  resources :stickers do
    collection do 
      get 'create_sticker' 
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check :only => [:index,:thank_you]

  def index

  end
  
  def thank_you
  
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="homeWrapper">
  <%= image_tag('welcome.png',:alt => "Design & create QR stickers for your products") %>
  <%= link_to image_tag('get_started_bt.png'),assets_path, :title => 'Get Started' %>
</div>

app/views/home/thank_you.erb
<div class="home_sec">
  <div class="text">Thank You! <%= flash[:message] %> </div>
    <label class="center_span">Go back to Home</label>
    <div class="wrp_btn">
      <div class="d_button"> 
       <%= link_to raw(tag(:img,:src => image_path('home.png'),:alt => "img_home",:style => "vertical-align:middle")),home_path ,:style => "width:86px"%>
      </div>
    </div>
  </div>
</div>