config/routes.rb
GenQR::Application.routes.draw do 

  
  
  resources :assets  do 
    member do
      get 'remove_template'
      get 'all_sticker'
      get 'download_sticker'
      get 'validation_error'
      get 'print_sticker'
    end
    collection do 
      get 'failed_asset'
    end
  end
  
  resources :sticker_templates do
    member do 
      get 'sample_template'
      put 'update_copy'
    end  
  end

  mount Resque::Server.new, :at => "/resque"

  
  
  match '/welcome' => "home#index",:as => :home
  match '/thank_you' => "home#thank_you",:as => :thank_you  

  devise_for :users

  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout
  end

  resources :users 
  

  
  resources :products do 
    member do 
      get 'qrcode_image'
      get 'regenerate_qrcode'
    end
  end
  
  resources :stickers do
    collection do 
      get 'create_sticker' 
    end
  end

end

app/models/sticker_template.rb
class StickerTemplate < ActiveRecord::Base
  has_many :stickers ,:dependent => :destroy
  has_many :assets,:through => :stickers
  validates :name,:presence => true,:uniqueness => {:scope => :user_id }
  validates :width,:height,:presence => true
  
  validates :width,:numericality => { :only_integer => true,:message => "must be number" },:unless => "width.nil?"
  
  validates :height,:numericality => { :only_integer => true,:message => "must be number" },:unless => "height.nil?"
  
  validates :logo_image,:logo_width,:logo_height,:presence => true,:if => :logo_exists?
  
  validates :logo_width,:numericality => {:only_integer => true ,:message => "must be number"},:if => :logo_exists_and_width_nil? 
  
  validates :logo_height,:numericality => {:only_integer => true ,:message => "must be number"},:if => :logo_exists_and_height_nil?
  
  validates :qrcode_width,:qrcode_height ,:presence => true
  
  validates :qrcode_width,:numericality => { :only_integer => true ,message: "must be number"} ,:unless => "qrcode_width.nil?"
  
  validates :qrcode_height,:numericality => { :only_integer => true ,message: "must be number"} ,:unless => "qrcode_height.nil?"
  
  validates :unit_font,:presence => true,:if => :unit_exists?
  
  validates :unit_font ,:numericality => { :only_integer => true ,:message => "must be number"} ,:if => "unit? && !unit_font.nil?"
  
  validates :note_font,:presence => true,:if => :note_exists?
  
  validates :note_font ,:numericality => { :only_integer => true ,:message => "must be number"},:if => "notes? && !note_font.nil?"
  
  validates :serial_number_font,:presence => true,:if => :serial_number_exists?
  
  validates :serial_number_font ,:numericality => { :only_integer => true ,:message => "must be number"},:if => "serial_number? && !serial_number_font.nil?"
  
  validate :validate_qrcode_width_height ,:unless => "(qrcode_height.nil? || qrcode_width.nil?)"
  
  belongs_to :user 
 
  mount_uploader :logo_image ,LogoUploader
  Position = {"Left" => "left","Center" => "center","Right" => "right" }
  before_save :remove_form_tag ,:on => :update
 
  after_save :resize_image ,:if => :logo_parameter_changed?
  before_save :set_note_container , :if => "notes? && note_width.nil? && note_height.nil?"
  before_save :set_unit_container,:if => "unit? && unit_width.nil? && unit_height.nil?"
  FontStyle = %w(Arial Thamo)
  
  scope :default_sticker_template ,where("default_template = ?",true)

  DefaultOptions = {
    :default_template => true,
    :width  =>  500, 
    :height => 240,
    :qrcode => true,
    :qrcode_width => 218,
    :qrcode_height => 171,
    :logo   =>  false,
    :footer => true,
    :notes => true,
    :note_width => 200,
    :note_height => 21,
    :note_font => 10,
    :note_font_style =>"Arial",
    :note_position => "center",
    :unit  => true,
    :unit_width => 226,
    :unit_height => 17,
    :unit_font => 15,
    :unit_font_style => "Thamo",
    :unit_position => "left",
    :body   => <<BODY 
    
    <div class="template ui-resizable" id="container" style="top: 0px; left: 0px; width: 500px; height: 240px; ">

    <div class="qrcode ui-resizable ui-draggable" id="qrcode" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; position: absolute; width: 218px; height: 171px; left: 124px; top: 10px; ">
       {{{ QRCODE }}}
    <div class="ui-resizable-handle ui-resizable-e"></div><div class="ui-resizable-handle ui-resizable-s"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 1001; "></div></div>
 
        <div class="notes ui-resizable ui-draggable" id="notes" style="font-size: 10px; text-align: center; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; position: absolute; width: 200px; height: 21px; left: 20px; top: 197px; ">
          {{{ NOTES }}}
        <div class="ui-resizable-handle ui-resizable-e"></div><div class="ui-resizable-handle ui-resizable-s"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 1001; "></div></div>
        <div class="unit ui-resizable ui-draggable" id="unit" style="font-size: 15px; text-align: left; margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px; position: absolute; width: 226px; height: 17px; left: 236px; top: 198px; ">
          {{{ UNIT }}}
        <div class="ui-resizable-handle ui-resizable-e"></div><div class="ui-resizable-handle ui-resizable-s"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 1001; "></div></div>
 <div class="ui-resizable-handle ui-resizable-e ui-draggable"></div><div class="ui-resizable-handle ui-resizable-s ui-draggable"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se ui-draggable" style="z-index: 1001; "></div></div> 
BODY
  }
  
  def remove_form_tag
   if !body.nil?
    body.gsub!(/<form.+/,"")  unless  body.scan(/<form.+/).empty? 
   end 
  end
  
  
  private
   
  def logo_exists?
    self.logo
  end
  
  def unit_exists?
    self.unit
  end
  
  def note_exists?
    self.notes
  end

  def serial_number_exists?
    self.serial_number
  end
  
  def logo_parameter_changed?
    self.logo && (self.logo_width_changed? || self.logo_height_changed?) 
  end
  
  def resize_image
    img = ImageList.new(File.join(Rails.root,'public',self.logo_image.to_s))
    img.resize!(self.logo_width.to_i, self.logo_height.to_i)
    img.write(File.join(Rails.root,'public',self.logo_image.to_s))
  end

  def validate_qrcode_width_height
    self.errors[:qrcode] << "Maximum Allocated size for QRCODE is 500x500" if self.qrcode_width > 500 || self.qrcode_height > 500
  end
  
  def set_note_container
    self.note_width = (self.width.to_i * 0.4).to_i
    self.note_height = self.note_font.to_i + 2
  end
  
  def set_unit_container
    self.unit_width = (self.width.to_i * 0.4).to_i
    self.unit_height = self.unit_font.to_i + 2
  end
  
  def logo_exists_and_width_nil? 
     self.logo && !self.logo_width.nil?
  end
  
  def logo_exists_and_height_nil? 
    self.logo && !self.logo_height.nil?
  end
  
end

app/controllers/sticker_templates_controller.rb
class StickerTemplatesController < ApplicationController
  # GET /sticker_templates
  # GET /sticker_templates.json
  authorize_resource
  layout 'basic' ,:only => 'sample_template'
  def index
    @sticker_templates = current_user.sticker_templates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sticker_templates }
    end
  end

  # GET /sticker_templates/1
  # GET /sticker_templates/1.json
  def show
    @sticker_template = current_user.sticker_templates.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sticker_template }
    end
  end

  # GET /sticker_templates/new
  # GET /sticker_templates/new.json
  def new
    @sticker_template = current_user.sticker_templates.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sticker_template }
    end
  end

  # GET /sticker_templates/1/edit
  def edit
    @sticker_template = current_user.sticker_templates.find(params[:id])
  end

  # POST /sticker_templates
  # POST /sticker_templates.json
  def create
    @sticker_template = current_user.sticker_templates.new(params[:sticker_template])

    respond_to do |format|
      if @sticker_template.save
        format.html { redirect_to @sticker_template, notice: 'Sticker template was successfully created.' }
        format.json { render json: @sticker_template, status: :created, location: @sticker_template }
      else
        format.html { render action: "new" }
        format.json { render json: @sticker_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sticker_templates/1
  # PUT /sticker_templates/1.json
  def update
    @sticker_template = current_user.sticker_templates.find(params[:id])

    respond_to do |format|
      if @sticker_template.update_attributes(params[:sticker_template].merge(:body => nil))
        format.html { redirect_to @sticker_template }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def update_copy
    @sticker_template = current_user.sticker_templates.find(params[:id])

    respond_to do |format|
      if @sticker_template.update_attributes(params[:sticker_template])
        format.js { render :text => 'Sticker Template is updated successfully' ,:layout => false}
      end
    end
  end
  
  # DELETE /sticker_templates/1
  # DELETE /sticker_templates/1.json
  def destroy
    @sticker_template = current_user.sticker_templates.find(params[:id])
    asset =  @sticker_template.assets.first unless @sticker_template.assets.empty?
    
    @sticker_template.destroy
    
    unless asset.nil?
      asset.stickers.create(:sticker_template_id => default_template.id)
    end
    respond_to do |format|
      format.html { redirect_to sticker_templates_url,notice: 'Asset Deleted',klass: 'success' }
      
    end
  end
  
  def sample_template
    @sticker_template = current_user.sticker_templates.find(params[:id])
  end
  
  private
  
  def default_template
    current_user.sticker_templates.default_sticker_template.first
  end
  
end

app/helpers/sticker_templates_helper.rb
module StickerTemplatesHelper
end

app/views/sticker_templates/_form.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "template", :media => "screen" %>
<%end%>
    <div id="templateFormContainer" class="container">
        <h2>Your Template Option</h2>
          <div class="formContainer">
            <fieldset>
               <%= form_for(@sticker_template) do |f| %>
                <% if @sticker_template.errors.any? %>
                    <div class="msgContainer error">
                      <strong><%= pluralize(@sticker_template.errors.count, "Error") %> Occurred</strong>
                       <ol class="errorList">
                            <% @sticker_template.errors.full_messages.each do |msg| %>
                            <li><%= msg %></li>
                            <% end %>
                       </ol><!--errorList-->
                    </div><!--msgContainer-->
                <% end %>
              <ul class="formElements">
                <li>
                <div class="ovfl-hidden box">
                  <label class="tmplateLbl1">Template name<span>*</span></label>
                <%= f.text_field :name ,:placeholder =>  "Template Name",:class => "txtBox" %>
                </div>
                <div class="ovfl-hidden box">
                  <label class="lblMeasurment">Width</label>
                  <%= f.text_field :width ,:placeholder => "Width",:class => "txtBox smalltxtbox" %>
                  <!-- <div class="csm1 fl"></div> -->
                    <label class="lblMeasurment">Height</label>
                    <%= f.text_field :height ,:placeholder => "Height",:class => "txtBox smalltxtbox" %>
                  <!-- <div class="csm1 fl"></div> -->
                </div>
                <div class="ovfl-hidden box" >
                  <label class="tmplateLbl1 fl">Logo</span></label>
                  <label class="fr rightCheckBox"><span id="logoo">Yes</span>
                    <%= f.check_box :logo ,:class => "checkBox" ,:id=> "logoo" %>

                  </label>
                </div>
                <div class="DisplayNone logoo">
                  <div class="ovfl-hidden box">  
                      <div class="ovfl-hidden"> </div>
                        <div class="DisplayNone">
                          <%= f.file_field :logo_image %>
                          <%= f.hidden_field :logo_image_cache %>
                          <p class="paraFile">(jpg, gif, png)</p>
                      </div>
                  </div>
                  <div class="ovfl-hidden box">
                      <label class="lblMeasurment">Width</label>
                      <%= f.text_field :logo_width ,:placeholder => "Logo Width" ,class: "txtBox smalltxtbox"%>
                    <!-- <div class="csm1 fl">px</div> -->
                      <label class="lblMeasurment">Width</label>
                       <%= f.text_field :logo_height ,:placeholder => "Logo Width" ,class: "txtBox smalltxtbox"%>
                    <!-- <div class="csm1 fl">px</div> -->
                  </div>
                </div>
                <div class="ovfl-hidden box marginNone">
                  <label class="tmplateLbl1">QR Code</label>
                </div>
                <div class="ovfl-hidden box">
                    <label class="lblMeasurment">Width</label>
                    <%= f.text_field :qrcode_width,:placeholder => "Qrcode Width" ,class: "txtBox smalltxtbox" %>
                    <label class="lblMeasurment">Height</label>
                    <%= f.text_field :qrcode_height,:placeholder => "Qrcode Height" ,class: "txtBox smalltxtbox" %>
                </div>
                <div class="ovfl-hidden box"> </div>
                <div class="ovfl-hidden box">
                  <label class="tmplateLbl1 fl">Footer</label>
                  <label class="fr rightCheckBox"><span id="footur">Yes</span>
                  <%= f.check_box :footer ,:class=>"checkBox" ,:id => "footur" %>
                  </label>
                </div>
                <div class="ovfl-hidden box DisplayNone footur">
                  <div class="ovfl-hidden">
                    <ul class="checkBoxlist">
                      <li>
                        <label>
                          <%= f.check_box :notes ,:class=>"lblCheckBox" ,:id=>"notes" %>
                          <span class="span1"><span style="color:black">Notes</span> (First 25 characters will be displayed)</span></label>
                      </li>
                      <li class="DisplayNoneLi">
                        <div class="ovfl-hidden notes">
                          <label class="tmplateLbl1">Font</label>
                          <div class="fl spaceRight">
                            <%= f.text_field :note_font,:class => "fontSize" %>
                          </div>
                          <div class="styled-select2 fl">
                           <%= f.select :note_font_style,options_for_select(StickerTemplate::FontStyle,@sticker_template.note_font_style),{},:class => "Big" %>
                          </div>
                         <div class="fl ovfl-hidden note_position">
                            <a class="textAlight fl left" href="#" data-position="left" data-id="note_position">
                                <img alt="imgleft" src="/assets/left.png">
                             </a>
                             <a class="fl textAlight center" href="#" data-position="center" data-id="note_position">
                                <img alt="centerImg" src="/assets/center.png">
                              </a>
                              <a class="fl textAlight right" href="#" data-position="right" data-id="note_position">
                                <img alt="rightImg" src="/assets/right.png">
                              </a>
                              <%= f.hidden_field :note_position ,:id => "note_position" %>
                         </div>
                        </div>
                      </li>
                      <li>
                        <label>
                           <%= f.check_box :unit ,:class=>"lblCheckBox" ,:id=>"unit" %>
                          
                          <span class="span1"><span style="color:black">Unit</span> (First 25 characters will be displayed)</span></label>
                      </li>
                      <li class="DisplayNoneLi">
                        <div class="ovfl-hidden unit">
                          <label class="tmplateLbl1">Font</label>
                          <div class="fl spaceRight">
                            <%= f.text_field :unit_font,:class => "fontSize" %>
                          </div>
                          <div class="styled-select2 fl">
                             <%= f.select :unit_font_style,options_for_select(StickerTemplate::FontStyle,@sticker_template.unit_font_style),{},:class => "Big" %>
                            
                          </div>
                          <div class="fl ovfl-hidden unit_position">
                            <a class="textAlight fl left" href="#" data-position="left" data-id="unit_position">
                              <img alt="imgleft" src="/assets/left.png">
                             </a>
                            <a class="fl textAlight center" href="#" data-position="center" data-id="unit_position">
                             <img alt="centerImg" src="/assets/center.png">
                            </a>
                            <a class="fl textAlight right" href="#" data-position="right" data-id="unit_position">
                              <img alt="rightImg" src="/assets/right.png" >
                            </a>
                            <%= f.hidden_field :unit_position ,:id => 
"unit_position" %>
                          </div>
                        </div>
                      </li>

                      <li>
                        <label>
                           <%= f.check_box :serial_number ,:class=>"lblCheckBox" ,:id=>"serial_number" %>
                          
                          <span class="span1"><span style="color:black">Serial Number</span> (First 25 characters will be displayed)</span></label>
                      </li>
                      <li class="DisplayNoneLi">
                        <div class="ovfl-hidden serial_number">
                          <label class="tmplateLbl1">Font</label>
                          <div class="fl spaceRight">
                            <%= f.text_field :serial_number_font,:class => "fontSize" %>
                          </div>
                          <div class="styled-select2 fl">
                             <%= f.select :serial_number_style,options_for_select(StickerTemplate::FontStyle,@sticker_template.serial_number_style),{},:class => "Big" %>
                            
                          </div>
                          <div class="fl ovfl-hidden serial_number_position">
                            <a class="textAlight fl left" href="#" data-position="left" data-id="serial_number_position">
                              <img alt="imgleft" src="/assets/left.png">
                             </a>
                            <a class="fl textAlight center" href="#" data-position="center" data-id="serial_number_position">
                             <img alt="centerImg" src="/assets/center.png">
                            </a>
                            <a class="fl textAlight right" href="#" data-position="right" data-id="serial_number_position">
                              <img alt="rightImg" src="/assets/right.png" >
                            </a>
                            <%= f.hidden_field :serial_number_position ,:id => 
"serial_number_position" %>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              <% if @sticker_template.new_record? %>
                  <%= f.submit "Create Template",:class => "button" %>
                <%else%>
                  <%= f.submit "Update Template",:class => "button" %>
                <%end%>
            </li>
          </ul><!--formelements-->
          <%end%>
          </fieldset>
        </div><!--formContainer-->
    </div>
<%= javascript_tag do %>
  $(document).ready(function() {
      $("input[type=checkbox]").bind('click',function() {
         var klass = this.id;
         if ($(this).is(':checked')) { 
           $("div."+klass).show();
           $("span#"+klass).html("Yes");
         }
         else {
         $("div."+klass).find("input[type=checkbox]").removeAttr("checked")
         $("div."+klass).hide();
         $("span#"+klass).html("No");
        }
     })
     $("input[type=checkbox]").not(':checked').each(function(index,element) {
        var klass = element.id;
        $("div."+klass).hide();
        $("span#"+klass).html("No");
     })
    
    $("a.left,a.center,a.right").bind('click',function() {
       var position = $(this).data("position");
       var id = $(this).data("id");
       $('div.'+id).find("a.active").removeClass("active");
       $(this).addClass("active");
       $("input#"+id).val(position); 
       return false;
    })  
    
    $('input#note_position,input#unit_position').each(function(index,element) {
       var value = $(element).val();
       if (typeof(value) == "undefined" || value == "") {
         value = "left" ; 
         $(this).val("left");
       }
       $("div."+element.id).find("a."+value).addClass("active");   
    })

    $('<span>PX</span>').insertAfter('.formElements input[placeholder="Width"], .formElements input[placeholder="Height"], .formElements input[placeholder="Logo Width"], .formElements input[placeholder="Logo Height"], .formElements input[placeholder="Qrcode Width"], .formElements input[placeholder="Qrcode Height"]');
  })
<%end%>

app/views/sticker_templates/edit.html.erb
<%= render 'form' %>

app/views/sticker_templates/index.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "template", :media => "screen" %>
<%end%>

<%= link_to raw('<span>Create Template</span>') ,new_sticker_template_path, :class => 'button add' %>

    <ul class="templateList">
        <% @sticker_templates.each do |sticker_template| %>
        <li>
            <a href="#" data-url="<%= sample_template_sticker_template_path(sticker_template, :view_only => 1) %>" data-width="<%= sticker_template.width.to_i+20 %>" data-height="<%= sticker_template.height.to_i+20 %>">
                <%= sticker_template.name %>
                <span>Click me</span>
            </a>
            <% unless sticker_template.default_template %>
            <div class="templateActions clearfix">
                <%= link_to raw('Edit Template'),edit_sticker_template_path(sticker_template),:class => "edit"%>
                <%= link_to raw('Delete Template'),sticker_template,method: 'delete',confirm: 'Do you want to delete this template' ,class: "delete" %>
            </div><!--templateActions-->
            <%end%>
        </li>
        <%end%>
    </ul><!--templateList-->
       
<%= javascript_tag do %>
  $(document).ready(function() {
    $('.templateList > li > a').bind('click',function() {
      var iwidth=$(this).data('width');
      var iheight=$(this).data('height');
      var url=$(this).data('url');
      $.modal('<iframe src="' + url + '" height="'+iheight+'" width="'+iwidth+'" style="border:0" scrolling="no">', { overlayClose:true,
      overlayCss: {backgroundColor: '#333'},
      containerCss: {backgroundColor: '#fff', border: '2px solid #000;'}
    })
   }); 
 })
<%end%>

app/views/sticker_templates/new.html.erb
<%= render 'form' %>

app/views/sticker_templates/sample_template.erb
<% if @sticker_template.body.nil? %>
<div class="template" id="container" style="width:<%= @sticker_template.width %>px;height:<%= @sticker_template.height %>px;">
  <% if @sticker_template.logo? %>
    <div id="logo" class="logo ui-widget-content" style="width:<%= @sticker_template.logo_width%>px;height:<%= @sticker_template.logo_height %>px;margin:0px;position:relative;">
       {{{ LOGO }}}
    </div>
 <%end%>

    <div class="qrcode" id="qrcode" style="width:<%=@sticker_template.qrcode_width %>px;height:<%= @sticker_template.qrcode_height%>px;margin:0px;position:relative;">
       {{{ QRCODE }}}
    </div>
 
  <% if @sticker_template.footer? %>
    <% if @sticker_template.notes? %>
        <div class="notes" id="notes" style="width:<%= @sticker_template.note_width %>px;height:<%= @sticker_template.note_height %>px;font-style:<%= @sticker_template.note_font_style %>;font-size:<%= @sticker_template.note_font %>px;text-align:<%= @sticker_template.note_position %>;margin:0px;position:relative;">
          {{{ NOTES }}}
        </div>
     <%end%>
    <% if @sticker_template.unit? %>
        <div class="unit" id="unit" style="width:<%= @sticker_template.unit_width %>px;height:<%= @sticker_template.unit_height %>px;font-style:<%= @sticker_template.unit_font_style %>;font-size:<%= @sticker_template.unit_font %>px;text-align:<%= @sticker_template.unit_position %>;margin:0px;position:relative;">
          {{{ UNIT }}}
        </div>
     <%end%> 
    <% if @sticker_template.serial_number? %>
        <div class="serial_number" id="serial_number" style="width:<%= @sticker_template.serial_number_width %>px;height:<%= @sticker_template.serial_number_height %>px;font-style:<%= @sticker_template.serial_number_style %>;font-size:<%= @sticker_template.serial_number_font %>px;text-align:<%= @sticker_template.serial_number_position %>;margin:0px;position:relative;">
          {{{ SERIAL_NUMBER }}}
        </div>
     <%end%> 
  <%end%>
 </div> 
<%else%>
  <%= raw @sticker_template.body %>
<%end%>

<%= form_tag update_copy_sticker_template_path(@sticker_template),:remote => true,:method => :put ,:class => "sticker" ,"data-type" => "html" do %>
  <%= hidden_field_tag 'sticker_template[width]',@sticker_template.width,:id => "template_width" %>
  <%= hidden_field_tag :height,@sticker_template.height,:name => 'sticker_template[height]' ,:id => "template_height" %>
  <%= hidden_field_tag 'sticker_template[logo_width]',@sticker_template.logo_width,:id => "logo_width" %>
  <%= hidden_field_tag 'sticker_template[logo_height]',@sticker_template.logo_height ,:id => "logo_height" %>
  <%= hidden_field_tag 'sticker_template[qrcode_width]',@sticker_template.qrcode_width,:id => "qrcode_width" %>
  <%= hidden_field_tag 'sticker_template[qrcode_height]',@sticker_template.qrcode_height,:id => "qrcode_height" %>
  <%= hidden_field_tag 'sticker_template[note_width]',@sticker_template.note_width, :id => "notes_width" %>
  <%= hidden_field_tag 'sticker_template[note_height]',@sticker_template.note_height, :id => "notes_height" %>
  <%= hidden_field_tag 'sticker_template[unit_width]',@sticker_template.unit_width, :id => "unit_width" %>
  <%= hidden_field_tag 'sticker_template[unit_height]',@sticker_template.unit_height, :id => "unit_height" %>
  <%= hidden_field_tag 'sticker_template[unit_font]',@sticker_template.unit_font %>
  <%= hidden_field_tag 'sticker_template[serial_number_width]',@sticker_template.serial_number_width, :id => "serial_number_width" %>
  <%= hidden_field_tag 'sticker_template[serial_number_height]',@sticker_template.serial_number_height, :id => "serial_number_height" %>
  <%= hidden_field_tag 'sticker_template[serial_number_font]',@sticker_template.serial_number_font %>
  <%= hidden_field_tag 'sticker_template[note_font]',@sticker_template.note_font %>
  <%= hidden_field_tag :body ,nil,:class => "template_body",:name =>'sticker_template[body]' %>
  <%= submit_tag "sumbit",:style => "display:none",:class => "click_me" %>
<%end%>

app/views/sticker_templates/show.html.erb
<a href="#" class="button upload save"><span>Save Template</span></a>
<a href="#" class="button upload refresh"><span>Refresh</span></a>

<div class="blankDiv" style="float:right">&nbsp;</div>
<div class="alert alert-notice" style="text-align:center; clear: both;">
 Drag, drop and re-size elements to design your sticker template
</div>


<div style="text-align:center">
  <iframe id="ifrme" src="<%= sample_template_sticker_template_path(@sticker_template) %>" width="<%= @sticker_template.width.to_i+200 %>px" height="<%= @sticker_template.height.to_i+200 %>px" > </iframe>
</div>

<%= javascript_tag do %>
  $(document).ready(function(event) {
    $('.save').bind('click',function() {
      if (typeof(window.called) != "undefined")
        event.preventDefault();
      window.called = true;   
      ajaxLoading = new ajaxLoader(document.body, { classOveride: 'blue-loader'} );
      window.parent.$("#ifrme")[0].contentWindow.send_request();
    })
    
    $('.refresh').bind('click',function() {
     window.location.reload(); 
      return false;
    }) 
     
  })
  function call_me(data) {
   $('.alert-notice').html('<strong>'+data+'</strong>')
   if (ajaxLoading) { ajaxLoading.remove(); }
    window.setTimeout(function() {
      window.document.location = '/sticker_templates'
     }, 1000);
  }
<%end%>