config/routes.rb
GenQR::Application.routes.draw do 

  
  
  resources :assets  do 
    member do
      get 'remove_template'
      get 'all_sticker'
      get 'download_sticker'
      get 'validation_error'
      get 'print_sticker'
    end
    collection do 
      get 'failed_asset'
    end
  end
  
  resources :sticker_templates do
    member do 
      get 'sample_template'
      put 'update_copy'
    end  
  end

  mount Resque::Server.new, :at => "/resque"

  
  
  match '/welcome' => "home#index",:as => :home
  match '/thank_you' => "home#thank_you",:as => :thank_you  

  devise_for :users

  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout
  end

  resources :users 
  

  
  resources :products do 
    member do 
      get 'qrcode_image'
      get 'regenerate_qrcode'
    end
  end
  
  resources :stickers do
    collection do 
      get 'create_sticker' 
    end
  end

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_many :products,:dependent => :destroy
  has_many :validation_errors ,:dependent => :destroy
  validates :name,:asset,:presence => true 
  has_many :stickers ,:dependent => :destroy
  has_many :sticker_templates,:through => :stickers
  belongs_to :user
  mount_uploader :asset,AssetUploader

  scope :processing_qrcode , where('status =? and processed =?','successful',false) 
  
  def failed?
    self.status == "failed"
  end
  
  def clear_validation_errors
    self.validation_errors.destroy_all
  end  
  
  
  def post_process
    download_file_from_s3_and_process
  end
  
  def create_stickers
    self.stickers.create(:sticker_template_id => default_template.id)
  end
  
  def filename
    asset.filename_with_pdf
  end
  
 private  
 
  def default_template
    StickerTemplate.where('name=? and user_id=?',"Default Template",self.user_id).first 
  end

  def download_file_from_s3_and_process
    begin
      create_directory
      download_file
      process_the_csv_file
    rescue => e
      Rails.logger.info "Failed Citing error #{e}"
      self.update_attributes(:status => 'failed',:error_encountered => e.to_s,:uploaded_at => DateTime.now)
    ensure
      remove_directory
    end
  end
 
  def process_the_csv_file
    product_attributes = []
    product_value = [] 
    product_hash  = []
    validation_errors  = []
    make_model_serial_combination = []
    vin_no = []
    row_no = 0
    make_index = 0
    model_index = 0
    serial_number_index = 0
    vin_index = 0
    times = 0
    
    
    CSV.foreach(File.join($DOWNLOAD_DIRECTORY,id.to_s,self.asset.filename.to_s)) do |row|
      row_no +=1
      row_records = row.collect { |record| record.strip unless record.nil? }
      if (row.empty? || row_records.length == 1 && row_records[0].empty?)
        next  
      end
      
      if product_attributes.empty?
        product_attributes = row.collect(&:strip).collect(&:downcase)
        vin_index = product_attributes.index('vin')
        make_index = product_attributes.index('make')
        model_index = product_attributes.index('model')
        serial_number_index = product_attributes.index('serial_number')
        next
      end
      
      record_hash = Hash.new
      
      row.each_with_index do |record,index|
        record_hash.merge!(product_attributes[index].to_sym => record)  
      end
      
      record_hash.merge!(:asset_id => self.id,:user_id => self.user_id)
      
      product = Product.new(record_hash)
     
      if product.valid? && (row.length == product_attributes.length) && (row[vin_index].nil? ? !make_model_serial_combination.compact.include?(row[make_index].to_s+row[model_index].to_s+row[serial_number_index].to_s) : !vin_no.compact.include?(row[vin_index]))   
        product_hash << row.push(self.id).push(self.user_id)
        make_model_serial_combination << row[make_index].to_s+row[model_index].to_s+row[serial_number_index].to_s
        vin_no << row[vin_index] 
      else
        times += 1
        product.errors.add :base, 'Entire row is blank' if !row.join.gsub!(',','').present?
        product.errors.add :base,"The given rows values doesnot match the attributes supplied" if row.length != product_attributes.length 
        #product.errors.add :vin,"There is already this 'vin' present in the current file" if !row[vin_index].nil? && vin_no.compact.include?(row[vin_index])
        #product.errors.add :base,"The combination of make,model,serial_number is not unique i.e already present" if row[vin_index].nil? && make_model_serial_combination.compact.include?(row[make_index].to_s+row[model_index].to_s+row[serial_number_index].to_s)
        validation_errors << [row_no,product.errors.messages.to_yaml,self.id]     
      end
      
      row_records,product,record_hash=[nil,nil,nil]  
    end
    if times.zero?
    
      Product.import(product_attributes.push(:asset_id).push(:user_id),product_hash,:validate => false)
      self.update_attributes(:status => 'successful',:uploaded_at => DateTime.now)
      Rails.logger.info "Resque Command Initiated ........................." 
      Resque.enqueue(QrcodeGenerator,self.id)
      Rails.logger.info "Resque Command Running in Background ...................."
    else
      self.update_attributes(:status => 'failed',:uploaded_at => DateTime.now)
      ValidationError.import([:row_id,:error_encountered,:asset_id],validation_errors,:validate => false)
    end
    
  end
  
  
  def download_file
    Rails.logger.info "Downloading file from S3 ..."
    File.open(File.join($DOWNLOAD_DIRECTORY,id.to_s,self.asset.filename.to_s),'w+') do |file|
     file <<  $storage.directories.get($BUCKET).files.get(File.join(self.asset.store_dir,self.asset.filename)).body.force_encoding("UTF-8")
    end 
    Rails.logger.info "Downloaded file from S3 !!!"
  end
  
  def create_directory
    Rails.logger.info "Creating Directory ..."
    unless File.exists?(File.join($DOWNLOAD_DIRECTORY,id.to_s))
      FileUtils.mkdir_p File.join($DOWNLOAD_DIRECTORY,id.to_s)
    end  
    Rails.logger.info "Created Directory !!!"
  end
  
  def remove_directory
    Rails.logger.info "Removing Directory ..."  
    FileUtils.rm_r File.join($DOWNLOAD_DIRECTORY,id.to_s) if File.exists?(File.join($DOWNLOAD_DIRECTORY,id.to_s))
   Rails.logger.info "Removed Directory !!!"  
  end
  
  
 
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController

  authorize_resource
  before_filter :load_asset ,:only => [:edit,:update,:show,:destroy,:all_sticker,:download_sticker,:validation_error]
  #layout 'sticker',:only => [:all_sticker,:download_sticker]
  layout 'sticker',:only => [:download_sticker]
  def index
    
    @assets = current_user.assets.where('status=?','successful').order('updated_at desc').includes('sticker_templates')
    @sticker_templates = current_user.sticker_templates
  end
  
  def failed_asset
    @assets = current_user.assets.where('status=?','failed').order('updated_at desc')
    respond_to do |format|
      if request.xhr?
        format.js { render :partial => 'failed_asset' }
      else
        format.html 
      end
    end
  end
  
  def create
    @asset = current_user.assets.new(params[:asset])
    respond_to do |format|
      if @asset.save
        flash[:message] = "Asset Create Successfully"
        @asset.post_process
        if @asset.failed?
          flash[:notice] = 'Error Uploading Asset'
          flash[:klass] = 'alert-error' 
          format.html { redirect_to failed_asset_assets_path }
        else
          @asset.create_stickers
          flash[:notice] = 'Successfully Uploaded Asset'
          flash[:klass] = 'alert-success'
          format.html { redirect_to assets_path } 
        end  
      else
        format.html { render action: 'new' }
      end
    end  
  end

  def new
    @asset = current_user.assets.new
  end
  
  def edit 
   
  end

  def validation_error
    @validation_errors  = @asset.validation_errors
    respond_to do |format|
      format.js { render :partial => 'validation_error' }
    end
  end
  
  def update
    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        flash[:message] = "Asset Updated Successfully"
        @asset.clear_validation_errors
        @asset.post_process
        if @asset.failed?
          flash[:notice] = 'Error Uploading Asset' 
          flash[:klass] = 'alert-error'
          format.html { redirect_to failed_asset_assets_path}
        else
          flash[:notice] = 'Successfully Uploaded Asset'
          flash[:klass] = 'alert-success'
          format.html { redirect_to assets_path}
        end  
      else
        format.html { render action: "edit" }
      end 
    end
  end

  def show
    @products = @asset.products
  end  
  
  
  def destroy
    respond_to do |format|
     redirect_page = @asset.failed?
      if @asset.destroy
       flash[:notice] = 'Successfully Destroyed Asset'
       flash[:klass] = 'alert-success' 
       if redirect_page
         format.html { redirect_to failed_asset_assets_path }
       else
        format.html { redirect_to assets_path}
       end 
      end
    end
  end

  def remove_template
    @asset = Asset.find(params[:id])
    respond_to do |format|
      @asset.stickers.destroy_all
      @asset.stickers.create(:sticker_template_id => params[:sticker_template_id])
      format.html { render text: "Successfully Applied Template" }
    end  
  end
  
  def print_sticker
    @asset = Asset.find(params[:id])
  end
 
  
  def all_sticker
    @product = @asset.products
    @sticker = @asset.stickers.first
  end
  
  
  
  def download_sticker
    @product = params[:product_id].present? ? [@asset.products.find(params[:product_id])] : @asset.products
    @printer = params[:printer]
    @page_break = true if params[:page_break].present?
    @sticker = @asset.stickers.first
    send_data(to_pdf,:filename => @asset.filename,:type => "application/pdf")
  end
  
  private
  
  def load_asset
    @asset = current_user.assets.find(params[:id])
  end
  
  def to_pdf
    invoke = execute_command
    create_cookie_jar
    Rails.logger.info %Q{#{render_to_string(:layout => true).gsub('"', "'")}}
    result = IO.popen(invoke, "wb+") do |pdf|
      pdf.puts(%Q{#{render_to_string(:layout => true).gsub('"', "'")}})
      pdf.close_write
      pdf.gets(nil)
    end
    remove_cookie_jar
    return result
  end

 
  
  def binary_path
    WkhtmlToPdf
  end
  
  def execute_command
    binary_path + options 
  end
  
  def pdfkit_options
    case @printer
    when "A"
      {:print_media_type => true, :cookie_jar => "#{create_cookie_jar}", :dpi => 300, :margin_top => 0, :margin_right => 0, :margin_bottom => 0, :margin_left => 0, :page_width => 18, :page_height => 27, :custom_header => "cookie #{cookies}" }
    when "B"
      {:print_media_type => true, :cookie_jar => "#{create_cookie_jar}", :dpi => 300, :margin_top => 0, :margin_right => 0, :margin_bottom => 0, :margin_left => 0, :page_width => 58, :page_height => 87, :custom_header => "cookie #{cookies}" }
    else
      {:print_media_type => true, :cookie_jar => "#{create_cookie_jar}", :dpi => 300, :margin_top => 0, :margin_right => 0, :margin_bottom => 0, :margin_left => 0, :custom_header => "cookie #{cookies}" }
    end
  end
    
  def options
    if @printer.nil?
      return " --cookie-jar '#{create_cookie_jar}' --custom-header 'cookie' '#{cookies}' --dpi 300  --margin-top 0 --margin-bottom 0 --margin-right 0 --margin-left 0 --quiet - -"
    elsif @printer == "A"
      return " --cookie-jar '#{create_cookie_jar}' --custom-header 'cookie' '#{cookies}' --dpi 300  --page-width 18 --page-height 27 --margin-top 0 --margin-bottom 0 --margin-right 0 --margin-left 0 --quiet - -"
    elsif @printer == "B"
      return " --cookie-jar '#{create_cookie_jar}' --custom-header 'cookie' '#{cookies}' --dpi 300  --page-width 58 --page-height 87 --margin-top 0 --margin-bottom 0 --margin-right 0 --margin-left 0 --quiet - -"
    end 
  end
  
  def cookies
   cookie_value =  request.cookies[cookie_name]
   "#{cookie_name}=#{cookie_value}"
  end
  
  def cookie_name
    key = "_session_id"
    key = Rails.configuration.session_options[:key] if Rails.configuration.session_store.name == "ActionDispatch::Session::CookieStore"
    key
  end
  
  def create_cookie_jar
    unless File.exists?(File.join(Rails.root,'public',"#{current_user.first_name}_#{current_user.id}_cookies.wkhtmltopdf.txt"))
      File.open(File.join(Rails.root,'public',"#{current_user.first_name}_#{current_user.id}_cookies.wkhtmltopdf.txt"),'w+') do |file|
       file.write cookies+"; HttpOnly; domain=#{DOMAIN}; path=/;"
      end 
    end 
    File.join(Rails.root,'public',"#{current_user.first_name}_#{current_user.id}_cookies.wkhtmltopdf.txt")
  end
  
  def remove_cookie_jar
    File.delete File.join(Rails.root,'public',"#{current_user.first_name}_#{current_user.id}_cookies.wkhtmltopdf.txt")
  end
end

app/helpers/assets_helper.rb
module AssetsHelper 
  def generate_id
    if controller.action_name == "edit" || controller.action_name == "update"
      return "editModal"
    else
      return "myModal"
    end  
  end
  
  def generate_message
    msg = '<h4> Following Error Occurred </h4> <br/><ol>'
    msg += format_message
    msg += '</ol>'      
   end
   
   def join_error_message(error,message)
      error.concat(' : ').concat(message.join(' '))
   end
   
   def format_message
     listing = ''
     @asset.errors.messages.each do |error,message|
       listing += content_tag(:li,join_error_message(error.to_s,message))
     end   
     return listing
   end
   
   
   def selected_sticker_template(asset)
     asset.sticker_templates.first.id rescue nil
   end
   
   
   def display_error(error)
    error_obj = YAML.load(error.error_encountered)
    "<li style='padding-left:25px'> <label class='error_lbl4'>Row_id #{error.row_id} :- #{error_description(error_obj)} </label> </li>"
   end
  
  def error_description(obj)
    error_field = String.new

    obj.each do |key,value|
      error_field += "#{key} : #{value.join(',')}"
    end
    return error_field
  end
  
end

app/views/assets/_download.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<br/>
<div class="wrp_exportBtn" style="padding-left:30px">
    <div class="export fl">
      <a style="width:84px" href="<%= asset_path(@asset)%>" >
        <span class="left_arrow fl" style="padding-left:6px; width:21px;">&nbsp;</span>
          <span class="fl"> 
          <div class="clr" style="text-align:center">&nbsp;</div>
            Back
          </span> 
       </a>
    </div>
</div>    

app/views/assets/_failed_asset.erb
  <div class='bg_container'>
  <table class="tabular">
      <thead>
          <tr>
              <th>File Name</th>
              <th>Uploaded On</th>
              <th>Error</th>
              <th>Re-upload</th>
              <th>Delete</th>
          </tr>
      </thead>
      <tbody>
          <% @assets.each do |asset| %>
          <tr class='wrp_list1'>
              <td><a href="<%= asset.asset %>" class="link_f"><%= asset.name %> </a></td>
              <td><%= asset.updated_at %></td>
              <td><%= link_to 'ERROR' , validation_error_asset_path(asset),:remote => true ,"data-type" => "html" ,:class => "validation_errors" %></td>
              <td class="reUpload"><%= link_to raw('Re-upload an asset') ,edit_asset_path(asset) %></td>
              <td><%= link_to raw(image_tag('delete_img.png')),asset,method: 'delete',confirm: 'Are you Sure to want to delete this file' %></td>
          </tr>
          <%end%>
      </tbody>
  </table>
</div>

<%= javascript_tag do %>

  $(document).ready(function() {
     $('tr.wrp_list1').delegate('a.validation_errors','ajax:beforeSend',function(evt, xhr, settings){ 
     		ajaxLoading = new ajaxLoader(document.body, { classOveride: 'blue-loader'} );
     })
     
     $("tr.wrp_list1").delegate("a.validation_errors","ajax:success", function(evt, data, status, xhr) { 
      if (ajaxLoading) { ajaxLoading.remove(); }
       $("div.bg_container").replaceWith(data);
     })       
  })

<%end%>

app/views/assets/_form.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<div id="assetFormContainer" class="container">
    <% if @asset.new_record? %>
        <h2>Upload Asset File</h2>
    <%else%>
        <h2>Re-Upload Asset File</h2>
    <%end%>
    <div class="formContainer">
       <%= form_for @asset do |f| %>
         <% unless @asset.errors.empty? %>
            <div class="msgContainer error">
              <strong>Error Uploading File</strong>
                <%= content_tag(:ol, raw(content_error(:li,@asset.errors)),:class => 'errorList') %>
            </div>
        <% end %>
        <fieldset>
            <ul class="formElements">
                <li><%= f.text_field :name ,:id => "file_name",:placeholder => "File Name" %></li>
                <li>
                    <%= f.file_field :asset %>
                    <%= f.hidden_field :asset_cache %>
                </li>
                <li><div class="instruction"><strong>Note: </strong>Please upload .csv file</div></li>
                <li class="clearfix">
                    <%= link_to 'Back' ,:back, :class => 'button' %>
                    <%= f.submit "Upload"%>
                </li>
            </ul><!--formElements-->
        </fieldset>
        <% if @asset.new_record? %>
          <%= javascript_tag do %>
            $(document).ready(function() {
              $('input[type=file]').bind('change',function() {
                $('#file_name').val($(this).val().split(/(\\|\/)/g).pop());
            })
            })
            <%end%>
          <%end%>
        <%end%>
    </div><!--formContainer-->
</div><!--container-->

app/views/assets/all_sticker.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<%= render 'sticker' %>

app/views/assets/edit.html.erb
<%= content_for :head do %>
	<%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<%= render 'form' %>

app/views/assets/failed_asset.erb
<%= content_for :head do %>
    <%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<ul class="tabs">
    <li><%= link_to 'Successful Uploads',assets_path  %></li>
    <li class="active"><%= link_to 'Failed Uploads', failed_asset_assets_path %></li>
</ul><!--tabs-->
<% flag = true %>
<div class="assetsContainer">
<% if flash[:notice].blank? %>
  <div class="alert" style='display: none;'>
    <span></span>
  </div>
<%else%>
  <div class="alert <%= flash[:klass] %>" >
    <span><%= flash[:notice] %></span>
  </div>
<%end%>
<%= link_to raw('<span>Upload Asset</span>'),new_asset_path,:class => "button upload" =%>
<div id="uploadsContainer" class="container">
    <h2>Failed Uploads</h2>
    <%= render 'failed_asset' %>
</div><!--container-->
</div><!--assetsContainer-->

<%= javascript_tag do %>
  $(document).ready(function() {
      $(".selectDropbox").bind('change',function() {
          var url = $(this).data('url');
          var template_id = $(this).val();
          
          var loader ;
          if(template_id != "" && confirm('Are you sure you want to apply this template and remove old template')) {
            $.ajax({
              "context" : document.body,
              "url" : url,
              "type" : "GET",
              "data" : 'sticker_template_id='+template_id,
              "data-type" : "html",
              "beforeSend" : function(jqXHR, settings) {
                loader = new ajaxLoader(this,{classOveride: 'blue-loader',bgColor: '#000', opacity: '0.3'});
              }, 
              "success" : function(data, textStatus, jqXHR) {
                 $(".selectDropbox").data("id",template_id);
                 $('.alert').addClass('alert-success').removeClass('alert-error').html('<span>'+data+'</span>').show().fadeOut(5000);
              },
              "error" : function (jqXHR, textStatus, errorThrown) {
                 $('.alert').addClass('alert-error').removeClass('alert-success').html('<span>'+textStatus+'</span>').show().fadeOut(5000);
              },
              "complete" : function(jqXHR, textStatus) {
                loader.remove();
              } 
            })
            
          } 
        else {
            if(template_id=="") 
              alert("Please Select a Template");
            $(this).val($(this).data('id'));
          }    
      })
  })
  <% unless (current_user.assets.processing_qrcode.empty? && flag) %>
      window.setTimeout(function(){ window.location.reload();},10000);
  <%end%>  
<%end%>

app/views/assets/index.html.erb
<%= content_for :head do %>
    <%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<ul class="tabs">
    <li class="active"><%= link_to 'Successful Uploads',assets_path  %></li>
    <li><%= link_to 'Failed Uploads', failed_asset_assets_path %></li>
</ul><!--tabs-->
<% flag = true %>
<div class="assetsContainer">
<% if flash[:notice].blank? %>
  <div class="alert" style='display: none;'>
    <span></span>
  </div>
<%else%>
  <div class="alert <%= flash[:klass] %>" >
    <span><%= flash[:notice] %></span>
  </div>
<%end%>
<%= link_to raw('<span>Upload Asset</span>'),new_asset_path,:class => "button upload" =%>
<div id="uploadsContainer" class="container">
    <h2>Successful Uploads</h2>
    <table class="tabular">
        <thead>
            <tr>
                <th>File Name</th>
                <th>Uploaded On</th>
                <th>Template Stickers</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <% @assets.each do |asset| %>
            <tr>
                <td>
                    <!-- The Reson for setting '&' and not '&&' since  -->
                    <% if asset.processed? %>
                        <% flag = flag & true %>
                        <%= link_to asset.name, asset_path(asset) %>
                    <%else%>
                        <% flag = flag & false %>
                        <%= asset.name %>
                    <%end%>
                </td>
                <td><%= asset.updated_at.to_date %></td>
                  <% if asset.processed? %>
                    <td>
                      <%= select_tag("sticker_templates",options_from_collection_for_select(@sticker_templates,'id','name',:selected => selected_sticker_template(asset)),:prompt => "Choose Template" ,:class => "selectDropbox" ,"data-url" => remove_template_asset_path(asset),"data-id" => selected_sticker_template(asset)) %>
                  </td>
                  <td>
                        <%= link_to raw(image_tag('delete_img.png')),asset,method: 'delete',confirm: 'Are you sure to want to delete this file?' %>
                     
                  </td>
                <%else%>
                  <td>GENERATING QRCODE ....</td>
                  <td>&nbsp;</td>
                <%end%>
            </tr>
            <%end%>
        </tbody>
    </table>
</div><!--container-->
</div><!--assetsContainer-->

<%= javascript_tag do %>
  $(document).ready(function() {
      $(".selectDropbox").bind('change',function() {
          var url = $(this).data('url');
          var template_id = $(this).val();
          
          var loader ;
          if(template_id != "" && confirm('Are you sure you want to apply this template and remove old template')) {
            $.ajax({
              "context" : document.body,
              "url" : url,
              "type" : "GET",
              "data" : 'sticker_template_id='+template_id,
              "data-type" : "html",
              "beforeSend" : function(jqXHR, settings) {
                loader = new ajaxLoader(this,{classOveride: 'blue-loader',bgColor: '#000', opacity: '0.3'});
              }, 
              "success" : function(data, textStatus, jqXHR) {
                 $(".selectDropbox").data("id",template_id);
                 $('.alert').addClass('alert-success').removeClass('alert-error').html('<span>'+data+'</span>').show().fadeOut(5000);
              },
              "error" : function (jqXHR, textStatus, errorThrown) {
                 $('.alert').addClass('alert-error').removeClass('alert-success').html('<span>'+textStatus+'</span>').show().fadeOut(5000);
              },
              "complete" : function(jqXHR, textStatus) {
                loader.remove();
              } 
            })
            
          } 
        else {
            if(template_id=="") 
              alert("Please Select a Template");
            $(this).val($(this).data('id'));
          }    
      })
  })
  <% unless (current_user.assets.processing_qrcode.empty? && flag) %>
      window.setTimeout(function(){ window.location.reload();},10000);
  <%end%>  
<%end%>

app/views/assets/print_sticker.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>

<div id="printContainer" class="container">
    <h2>Select Print Option</h2>
    <div class="formContainer">
        <fieldset>
            <ul class="formElements">
                <li class="clearfix">
                    <input type="radio" name="options" data-url="<%= download_sticker_asset_path(@asset)%> ">
                    <label>Multiple Sticker per Page</label>
                </li>
                <li class="clearfix">
                    <input type="radio" name="options" data-url="<%= download_sticker_asset_path(@asset,:page_break => true)%>">
                    <label>One Sticker per Page</label>
                </li>
                <li class="clearfix">
                    <input type="radio" name="options" data-url="<%= download_sticker_asset_path(@asset,:printer => "A",:page_break => true)%>">
                    <label>PT-2340PC Printer</label>
                </li>
                <li class="clearfix">
                    <input type="radio" name="options" data-url="<%= download_sticker_asset_path(@asset,:printer => "B",:page_break => true)%>">
                    <label>QL-570 Printer</label>
                </li>
                <li class="clearfix">
                    <a class="button" href="#" id="download">Download</a>
                </li>
            </ul><!--formElements-->
        </fieldset>
    </div><!--formContainer-->
</div><!--container-->

<%= javascript_tag do %>
  $(document).ready(function(){
    function download_pdf(url) {
      window.location=url;
    }
    $("a#download").bind("click",function() {
        if (!$('input[type=radio]').is(':checked')) 
          alert("Please Select a options");
        else
          download_pdf($('input[type=radio]:checked').data("url"))  
         
       return false;   
    })
  })
<%end%>

app/views/assets/show.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag "assets", :media => "screen" %>
<%end%>
<a href="<%= all_sticker_asset_path(@asset) %>" class="button upload"><span>View All Stickers</span></a>
<a href="<%= print_sticker_asset_path(@asset) %>" class="button upload"><span>Print Stickers</span></a>
  <% if @products.qr_code_generation_failed.count > 0 %>
    <div class="flash" style="text-align:center;font-size:15px;padding-bottom:15px;color:#D00;"> 
      Failed QRCode Generation will be regenerated after a 30 minutes from now 
    </div>
  <%end%>
<div class="container">
    <h2>Asset Details</h2>
    <table class="tabular">
        <thead>
            <tr>
                <th>Make</th>
                <th>Model</th>
                <th>Serial Number</th>
                <th>VIN</th>
                <th>Unit</th>
                <th>QRCODE</th>
                <th>Sticker Template</th>
            </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
            <tr>
                <td><%= product.make %></td>
                <td><%= product.model %></td>
                <td><%= product.serial_number %></td>
                <td><%= product.vin %></td>
                <td><%= product.unit %></td>
                <td class="qrCode">
                   <% if product.processed? %> 
                     <%= image_tag(GOOGLE_CHART_API % [150,150,CGI.escape(product.qrcode_url)]) %>
                   <%else%>
                     <span class="error" style="color:red" title="<%= product.error_message %>" >Failed</span>
                   <%end%>
                  </td>
                  <td>
                    <% if product.processed? %>
                      <%= link_to 'View Sticker',product_path(product,:sticker_id => @asset.stickers.first) ,:class => "link_f" %>
                    <%else%>
                      <%= link_to 'Regenerate QRCODE',regenerate_qrcode_product_path(product),:class => "link_f" %>    
                    <%end%>
                  </td>
                </tr>
             <%end%>
        </tbody>
    </table>
</div><!--container-->

<%= javascript_tag do %>
  $(document).ready(function() {
     $("span.error").qtip({
        style: {
					classes: 'ui-tooltip-shadow ui-tooltip-red' 
				}
			})
  })
<%end%>