config/routes.rb
GenQR::Application.routes.draw do 

  
  
  resources :assets  do 
    member do
      get 'remove_template'
      get 'all_sticker'
      get 'download_sticker'
      get 'validation_error'
      get 'print_sticker'
    end
    collection do 
      get 'failed_asset'
    end
  end
  
  resources :sticker_templates do
    member do 
      get 'sample_template'
      put 'update_copy'
    end  
  end

  mount Resque::Server.new, :at => "/resque"

  
  
  match '/welcome' => "home#index",:as => :home
  match '/thank_you' => "home#thank_you",:as => :thank_you  

  devise_for :users

  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout
  end

  resources :users 
  

  
  resources :products do 
    member do 
      get 'qrcode_image'
      get 'regenerate_qrcode'
    end
  end
  
  resources :stickers do
    collection do 
      get 'create_sticker' 
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  check_authorization :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to home_url, :alert => exception.message
  end



  private
  def after_sign_in_path_for(resource)
    home_path
  end
  
  def after_sign_out_path_for(resource)
    login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_css_classes(css_class) 
    if css_class == container_classes
      return "active"
    else
      return ""
    end    
  end
  
  def container_classes
     pages = {
      "users#index"   => "user", 
      "users#create"  => "user",
      "users#new"     => "user",
      "users#edit"    => "user",
      "users#destroy" => "user",
      "home#index"    => "home",
      "home#thank_you" => "home",
      "products#show" => "asset",
      "assets#index"  => "asset",
      "assets#failed_asset" => "asset",
      "assets#create" => "asset",
      "assets#all_sticker" => "asset",
      "assets#update" => "asset",
      "assets#edit"   => "asset",
      "assets#show"   => "asset",
      "assets#new"    => "asset",
      "assets#print_sticker" => "asset",
      "sticker_templates#index" => "template",
      "sticker_templates#new" => "template",
      "sticker_templates#show" => "template",
      "sticker_templates#create" => "template",
      "sticker_templates#edit" => "template",
      "sticker_templates#update" => "template",
      "sticker_templates#destroy" => "template"
      
      
    } 
    
    pages["#{controller.controller_name}##{controller.action_name}"] 
  end
 
  def full_path(path=String.new)
    request.scheme+"://"+SERVER_DOMAIN+path
  end
  
  def qrimage(url=nil)
   #image_tag(qrcode_link(url))
   "<img alt='qrcode' src='#{raw qrcode_link(url)}' />"
  end
  
  def qrcode_link(url=nil)
    url ||= @product.qrcode_url
    GOOGLE_CHART_API % [@sticker.sticker_template.qrcode_width.to_i-10, @sticker.sticker_template.qrcode_height.to_i-10,CGI.escape(url)]
  end
  
  def logo_tag
    if @sticker.sticker_template.logo?
      image_tag(absolute_asset_path(@sticker.sticker_template.logo_image.to_s))
    end  
  end
  
  def content_error(tag,arry)
    wrapper = String.new
    if arry.is_a?(ActiveModel::Errors)
      arry.each do |error,description|
        wrapper += content_tag(tag,"#{error.capitalize} #{description}")
      end
    end
    return wrapper
  end

  def sticker_css_class
    @page_break ? "break" : "no-break" 
  end 

  def absolute_asset_path(path='')
    Rails.env=='development' ? path : request.scheme+"://"+SERVER_DOMAIN+path
  end


end

app/views/application/_header.erb
<div class="header clearfix">
    <a class="logo" href="/welcome" title="GENQR"><img src="/assets/logo.png" alt="GENQR"></a>
    <ul class="loginNav clearfix">
        <li><%= link_to current_user.name ,edit_user_path(current_user) %></li>
        <li><%= link_to 'Logout',logout_path ,:class =>"fl link1"%></li>
    </ul><!--loginNav-->
</div><!--header-->

<ul class="primaryNav clearfix">
    <li><%= link_to 'Home'.upcase,home_path ,:class => "f1 #{current_css_classes('home')}" %></li>
    <li>
        <% if current_user.admin? %>
        <%= link_to 'User'.upcase,users_path ,:class => "f1 #{current_css_classes('user')}" %>
        <%else%>
        <%= link_to 'User'.upcase,edit_user_path(current_user) ,:class => "f1 #{current_css_classes('user')}" %>
        <%end%>
    </li>
    <li><%= link_to 'Asset'.upcase,assets_path ,:class => "f1 #{current_css_classes('asset')}" %></li>
    <li><%= link_to 'Template'.upcase,sticker_templates_path ,:class => "f1 #{current_css_classes('template')}" %></li>
</ul><!--primaryNav-->